### ISSUE TITLE
Undo - u does not work in the latest version Consulo

### ISSUE THREAD

**Issue by likaci** [consulo/consulo-vim#1]
CMD + z works well but u doesn't work

I have tried to install the ideaVim plugin from official plugin site, but failed. 
Thank for your excellent work.

**Comment by VISTALL** [comment]
Hi. You can't use IDEA plugins inside Consulo due API change. 

I don't known when check this issue - sorry

**Comment by likaci** [comment]
@VISTALL Can you give me some info about port IDEA plugin to Consulo.
I'm glad to try fix this if I can.
Thank you.

**Comment by VISTALL** [comment]
Main problem of porting ideaVim to Consulo, its a status of **merge**, Consulo don't have automatic merge from IDEA, and Consulo very behind from IDEA. That why ideaVIM maybe required some new methods from IDEA, but they don't exists in Consulo

Some info i wrote here https://github.com/consulo/consulo/wiki/Migration-from-IntelliJ-IDEA

**Comment by VISTALL** [comment]
exception 

``` java
Consulo 1390 + Vim Emulator (maybe this commit version)
(JRE ver)1.8.0_101-b13

I could not launch with Vim Emulator that time I got following error message.
before time I was using Consulo with Vim Emulator.

`Plugin 'org.mustbe.consulo.vim' failed to initialize and will be disabled. Please restart Consulo.

java.lang.AssertionError
at com.maddyhome.idea.vim.group.KeyGroup.addNode(KeyGroup.java:350)
at com.maddyhome.idea.vim.group.KeyGroup.registerAction(KeyGroup.java:338)
at com.maddyhome.idea.vim.group.KeyGroup.registerAction(KeyGroup.java:321)
at com.maddyhome.idea.vim.group.KeyGroup.registerAction(KeyGroup.java:276)
at com.maddyhome.idea.vim.RegisterActions.registerNormalModeActions(RegisterActions.java:491)
at com.maddyhome.idea.vim.RegisterActions.registerActions(RegisterActions.java:44)
at com.maddyhome.idea.vim.VimPlugin.initComponent(VimPlugin.java:150)
at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:577)
at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:619)
at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:126)
at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:355)
at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:117)
at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:517)
at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:499)
at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:117)
at com.intellij.idea.MainImpl$1$1.run(MainImpl.java:39)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
at java.awt.EventQueue.access$400(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:697)
at java.awt.EventQueue$3.run(EventQueue.java:691)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:376)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by VISTALL** [comment]
I merged code from upstream. Try it.
